name: doc

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 100
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: marceloprado/has-changed-path@v1
        id: changed-src
        with:
          paths: package.json src
      - uses: pnpm/action-setup@v2.0.1
        if: steps.changed-src.outputs.changed == 'true'
        with:
          version: 7
      - name: Build docs
        if: steps.changed-src.outputs.changed == 'true'
        run: pnpm i && pnpm build:docs
      - name: Deploy to GitHub Pages
        if: steps.changed-src.outputs.changed == 'true'
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
          single-commit: true
